[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge", "nodefaults",
"https://prefix.dev/pixi-build-backends",]
platforms = ["win-64", "linux-64"]
requires-pixi = ">=0.70"

[feature.pkg-build.tasks]
build = { cmd = ["pixi", "publish", "--target-platform", "{{ pixi.platform }}", 
        "--target-dir", "build","--package-format", "conda"]}
publish = { cmd = ["pixi", "publish", "--target-platform", "{{ pixi.platform }}", 
            "--target-channel", "https://prefix.dev/hydrolog", "--package-format", "conda"]}

[tasks]

[dependencies]
pixi-build-cmake = "*"
gcc = ">=16.2.0,<16.3"
gfortran = ">=16.2.0,<16.3"
python = ">=3.14.7,<3.15"

[package]
name = "swatplus"
version = "62.0.0"
authors = [""]
description = "Soil and Water Assessment Tool (SWAT)"
documentation = "https://swatplus.gitbook.io/docs"
homepage = "https://swat.tamu.edu/"
license-file = "license.txt"
readme = "README.md"
repository = "https://github.com/swat-model/swatplus"
publish = true

[package.build]
backend = { name = "pixi-build-cmake" }
source = { url = "https://github.com/dtarb/TauDEM/archive/refs/tags/v5.5.0.tar.gz" }
config = { extra-args = ["-DCMAKE_BUILD_TYPE=Release",] }

[package.host-dependencies."if(host_platform == 'linux-64')"]

[package.build-dependencies."if(host_platform == 'linux-64')"]

[package.run-dependencies."if(host_platform == 'linux-64')"]

[package.host-dependencies."if(host_platform == 'win-64')"]

[package.build-dependencies."if(host_platform == 'win-64')"]

[package.run-dependencies."if(host_platform == 'win-64')"]

[package.run-exports.weak]
package = { path = "."}

[environments]
swatplus = {features = ["pkg-build","default"],  no-default-feature = true }
